### ISSUE TITLE
actividad 7 linea del tiempo

### ISSUE THREAD

**Issue by ARICELCASTRO1999** [SistemasTecTlaxiaco/actividad-7-ARICELCASTRO1999#1]
[LINEA DEL TIEMPO DE LAS WEBS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-ARICELCASTRO1999/files/9816990/LINEA.DEL.TIEMPO.DE.LAS.WEBS.pdf)

**Comment by 11042002** [comment]
Tu calificación es de: 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
